#!/bin/bash

pwd=`pwd`

[ -d data ] || mkdir data && sudo chown -R 200 data

# Default credentials are: admin / admin123

docker run --name nexus \
  -p 28081:8081 \
  -v ${pwd}/data:/nexus-data \
  -e INSTALL4J_ADD_VM_PARAMS="-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g" \
  --restart=unless-stopped \
  -m 1G --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d sonatype/nexus3:3.6.1
