#!/usr/bin/env bash

pwd=$(pwd)

sudo yum install kudu-master                  # Kudu master init.d service script and default configuration, port 8051

# start the kudu master service
sudo service kudu-master start

# set start the kudu master when the system starts
sudo chkconfig kudu-master on

## default configurations
# configurations: /etc/kudu/
# log files: /var/log/kudu/
# other details:
# --fs_data_dirs=/var/lib/kudu/master
# --fs_wal_dir=/var/lib/kudu/master
# --heap_profile_path=/tmp/kudu-master.3711
# --flagfile=/etc/kudu/conf/master.gflagfile
# --fromenv=log_dir
# --log_dir=/var/log/kudu
