#!/usr/bin/env bash

pwd=$(pwd)

wget http://archive.cloudera.com/kudu/redhat/7/x86_64/kudu/cloudera-kudu.repo

sudo mv cloudera-kudu.repo /etc/yum.repos.d/

sudo yum install kudu                         # Base Kudu files
#sudo yum install kudu-client0                 # Kudu C++ client shared library
#sudo yum install kudu-client-devel            # Kudu C++ client SDK
