#!/bin/bash

pwd=`pwd`

docker run --name nginx \
  -p 80:80 \
  -p 443:443 \
  -v ${pwd}/nginx.conf:/etc/nginx/nginx.conf:ro \
  -v ${pwd}/conf.d:/etc/nginx/conf.d:ro \
  -v ${pwd}/conf:/opt/nginx/conf:ro \
  -v ${pwd}/www/html:/var/www/html:rw \
  --restart=unless-stopped \
  -m 512M --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d nginx:1.17-alpine

  #-p 80:80 \ # this will be mapped to cloud LB 443
  #-p 8080:8080 \ # this only used for cloud LB 80 redirect (to LB:443)
  # -p 443:443 \ # https/ssl will be handled by cloud load balancer
