#!/bin/bash

pwd=`pwd`

docker run --name prometheus \
  -p 127.0.0.1:9090:9090 \
  --restart=unless-stopped \
  -m 256M --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d quay.io/prometheus/prometheus:latest
