#!/bin/bash -ex

pwd=`pwd`
#ver=$1
ver=$(<ver)

# [ -d nginx ] || git clone https://github.com/nginx/nginx.git
# cd nginx && git checkout release-1.17.9

if [ ! -d nginx-$ver ] 
then
    wget http://nginx.org/download/nginx-$ver.tar.gz
    tar xzf  nginx-$ver.tar.gz
fi

[ -d ngx_http_proxy_connect_module ] || git clone https://github.com/chobits/ngx_http_proxy_connect_module.git

cd nginx-$ver

patch -p1 < $pwd/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_101504.patch || true

    #--prefix=/usr/local/nginx \
    #--with-cc-opt=-Wno-error \
    #--with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
./configure \
    --user=www \
    --group=www \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-threads \
    --add-module=${pwd}/ngx_http_proxy_connect_module \
    --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid \
    --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=nginx --group=nginx --with-compat --with-file-aio --with-http_addition_module \
    --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module \
    --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module \
    --with-http_secure_link_module --with-http_slice_module \
    --with-http_sub_module --with-http_v2_module --with-mail \
    --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module \
    --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Wno-error -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
    --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' \
    && make

