#!/bin/bash

pwd=`pwd`

docker run --name nginx \
  -p 80:80 \
  -p 443:443 \
  -v ${pwd}/nginx.conf:/etc/nginx/nginx.conf:ro \
  -v ${pwd}/conf.d:/etc/nginx/conf.d:ro \
  -v /home/ptmind/workspace/www:/var/www/html:rw \
  --restart=unless-stopped \
  -m 512M --memory-swap -1 \
  --cpuset-cpus="0,1" \
  --link phpengine \
  -d nginx:1.9-alpine

