#!/bin/bash

pwd=`pwd`

[ -d jenkins_home ] || mkdir -p jenkins_home

docker run --name jenkins \
  -u root \
  -p 11080:8080 \
  -p 50000:50000 \
  -v ${pwd}/jenkins_home:/var/jenkins_home:rw \
  -v ${pwd}/conf/log.properties:/var/jenkins/conf/log.properties:ro \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --env JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins/conf/log.properties" \
  --restart=unless-stopped \
  -m 2G --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d jenkinsci/blueocean

  # --rm \
  # -d jenkins
  # -d jenkins:alpine

  # --env JENKINS_OPTS="--httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk" \
