#!/bin/bash

pwd=`pwd`

[ -d data ] || mkdir data

docker run --name rdb \
  -p 3306:3306 \
  -v ${pwd}/data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=R0ot \
  -e MYSQL_DATABASE=ptmind \
  -e MYSQL_USER=ptmind \
  -e MYSQL_PASSWORD=Ptmind2016 \
  --restart=unless-stopped \
  -m 1G --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d mysql:5.7 \
  --character-set-server=utf8mb4 \
  --collation-server=utf8mb4_unicode_ci

