#!/bin/bash

pwd=`pwd`

[ -d data ] || mkdir data
[ -d logs ] || mkdir logs

sudo chown 999:docker logs

docker run --name mysql \
  -p 3306:3306 \
  -v ${pwd}/data:/var/lib/mysql \
  -v ${pwd}/logs:/var/log/mysql \
  -v ${pwd}/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf \
  -e MYSQL_ROOT_PASSWORD=R0ot \
  -e MYSQL_DATABASE=gcp \
  -e MYSQL_USER=gcp \
  -e MYSQL_PASSWORD=gcp2020 \
  --restart=unless-stopped \
  -m 2G --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d mysql:8.0 \
  --character-set-server=utf8mb4 \
  --collation-server=utf8mb4_unicode_ci

