#!/bin/bash

docker run -d --name=netdata \
    -p 19999:19999 \
    -v /etc/passwd:/host/etc/passwd:ro \
    -v /etc/group:/host/etc/group:ro \
    -v /proc:/host/proc:ro \
    -v /sys:/host/sys:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --cap-add SYS_PTRACE \
    --security-opt apparmor=unconfined \
    -e DO_NOT_TRACK=1 \
    --restart=unless-stopped \
    -m 1G --memory-swap -1 \
    --cpuset-cpus="0,1" \
    netdata/netdata
