#!/bin/bash

pwd=`pwd`

[ -d data ] || mkdir data

docker run --name postgres \
  -p 5432:5432 \
  -v ${pwd}/data:/var/lib/postgresql/data \
  -e POSTGRES_DB=gcloud \
  -e POSTGRES_USER=dingo \
  -e POSTGRES_PASSWORD=Dingo2019 \
  --restart=unless-stopped \
  -m 1G --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d postgres:12

