#!/bin/bash

pwd=`pwd`

docker run --name esnginx \
  -p 80:80 \
  -p 443:443 \
  -v ${pwd}/nginx.conf:/etc/nginx/nginx.conf:ro \
  -v ${pwd}/cert.key:/opt/nginx/conf/cert.key:ro \
  -v ${pwd}/cert.crt:/opt/nginx/conf/cert.crt:ro \
  --restart=unless-stopped \
  -m 512M --memory-swap -1 \
  --cpuset-cpus="0,1" \
  -d nginx:1.17-alpine

