#!/usr/bin/env bash

pwd=$(pwd)

# CDH repo
wget https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
sudo mv cloudera-cdh5.repo /etc/yum.repos.d/

wget http://archive.cloudera.com/beta/impala-kudu/redhat/7/x86_64/impala-kudu/cloudera-impala-kudu.repo

sudo mv cloudera-impala-kudu.repo /etc/yum.repos.d/

sudo yum install impala-kudu # Base impala files
sudo yum install impala-kudu-server 
sudo yum install impala-kudu-catalog
sudo yum install impala-kudu-state-store
sudo yum install impala-kudu-shell
