#!/usr/bin/env bash

pwd=$(pwd)

# CDH repo
wget https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
sudo mv cloudera-cdh5.repo /etc/yum.repos.d/

sudo yum install impala # Base impala files
sudo yum install impala-server
sudo yum install impala-catalog
sudo yum install impala-state-store
sudo yum install impala-shell

## Post installtion config
# /etc/default/impala Set the --kudu_master_hosts=<master1>[:port],<master2>[:port],<master3>[:port] flag in the Impala service configuration. 
# /etc/impala/conf => core-site.xml  hdfs-site.xml  hive-site.xml
